Repository lblod/ember-submission-form-fields, pull requests merged in 2022-08, with the labels that each got.

#85 Resolve the AuToolbarGroup deprecation
  tests/dummy/app/templates/application.hbs
Labels: internal

#87 Replace browser-rdfib with rdflib v2
  addon/components/custom-submission-form-fields/bestuursorgaan-selector/edit.js
  addon/components/custom-submission-form-fields/bestuursorgaan-selector/show.js
  addon/components/custom-subsidy-form-fields/application-form-table/edit.js
  addon/components/custom-subsidy-form-fields/application-form-table/show.js
  addon/components/custom-subsidy-form-fields/climate-subsidy-costs-table.js
  addon/components/custom-subsidy-form-fields/climate-subsidy-costs-table/table-row-burgemeesters.js
  addon/components/custom-subsidy-form-fields/climate-subsidy-costs-table/table-row-custom-action.js
  addon/components/custom-subsidy-form-fields/climate-subsidy-costs-table/table-row-vastgoedplan.js
  addon/components/custom-subsidy-form-fields/climate-subsidy-costs-table/table-row-werf.js
  addon/components/custom-subsidy-form-fields/engagement-table/edit.js
  addon/components/custom-subsidy-form-fields/engagement-table/show.js
  addon/components/custom-subsidy-form-fields/estimated-cost-table/base-table.js
  addon/components/custom-subsidy-form-fields/estimated-cost-table/edit.js
  addon/components/custom-subsidy-form-fields/objective-table/edit.js
  addon/components/custom-subsidy-form-fields/objective-table/table-cell.js
  addon/components/custom-subsidy-form-fields/plan-living-together-table/edit.js
  addon/components/custom-subsidy-form-fields/plan-living-together-table/table-row.js
  addon/components/rdf-input-fields/concept-scheme-multi-select-checkboxes.js
  addon/components/rdf-input-fields/concept-scheme-multi-selector.js
  addon/components/rdf-input-fields/concept-scheme-radio-buttons.js
  addon/components/rdf-input-fields/concept-scheme-selector.js
  addon/components/rdf-input-fields/date-range.js
  addon/components/rdf-input-fields/date-time.js
  addon/components/rdf-input-fields/date.js
  addon/components/rdf-input-fields/files.js
  addon/components/rdf-input-fields/input-field.js
  addon/components/rdf-input-fields/numerical-input.js
  addon/components/rdf-input-fields/remote-urls/edit.js
  addon/components/rdf-input-fields/remote-urls/show.js
  addon/components/rdf-input-fields/simple-value-input-field.js
  addon/components/rdf-input-fields/vlabel-opcentiem.js
  package.json
  tests/dummy/app/components/test-form.js
  tests/dummy/app/routes/form.js
Labels: breaking

#91 Update to uuid v8
  package.json
Labels: internal

#93 Remove ember-test-selectors
  ember-cli-build.js
  package.json
Labels: internal

#86 Remove `@renderInPlace` from the ConceptSchemeSelector component
  addon/components/rdf-input-fields/concept-scheme-selector.hbs
Labels: internal

#95 Only use the lang string logic if the predicate is set
  addon/components/rdf-input-fields/simple-value-input-field.js
Labels: bug

#98 Improve the read-only mode of the Listing and SubForm components
  addon/components/listing.js
  addon/components/sub-form.hbs
  addon/components/sub-form.js
Labels: bug

#96 Make the PropertyGroup title level and skin configurable
  addon/components/property-group.hbs
  addon/components/property-group.js
  addon/models/property-group.js
Labels: enhancement
