Repository lblod/ember-submission-form-fields, pull requests merged in 2025-01, with the labels that each got.

#197 [DL-5449] Fix an issue with the "RemoteUrl" field
  addon/components/rdf-input-fields/remote-urls/edit.hbs
Labels: bug

#195 Fix "true" value handling in boolean components (checkbox/switch)
  addon/components/rdf-input-fields/checkbox.js
  addon/components/rdf-input-fields/switch.js
Labels: bug

#199 Add support for ember-concurrency v4 and power select v8
  ember-cli-build.js
  index.js
  package-lock.json
  package.json
  tests/dummy/app/templates/application.hbs
  tests/dummy/public/mockServiceWorker.js
Labels: enhancement

#200 Update to Ember 5.12 LTS
  .ember-cli
  .eslintignore
  .gitignore
  .npmignore
  .prettierignore
  .watchmanconfig
  .woodpecker/test-pr-scenario-ember-lts-4.12.yml
  CONTRIBUTING.md
  README.md
  addon/components/custom-submission-form-fields/bestuursorgaan-selector/edit.js
  addon/components/custom-submission-form-fields/bestuursorgaan-selector/show.js
  addon/components/form-section.js
  addon/components/listing.js
  addon/components/listing/list.hbs
  addon/components/listing/table.hbs
  addon/components/listing/table.js
  addon/components/rdf-form.js
  addon/components/rdf-input-fields/concept-scheme-multi-select-checkboxes.js
  addon/components/rdf-input-fields/concept-scheme-multi-selector.js
  addon/components/rdf-input-fields/concept-scheme-radio-buttons.js
  addon/components/rdf-input-fields/concept-scheme-selector.js
  addon/components/rdf-input-fields/date-range.js
  addon/components/rdf-input-fields/files.js
  addon/components/rdf-input-fields/input-field.js
  addon/components/rdf-input-fields/remote-urls/edit.hbs
  addon/components/rdf-input-fields/remote-urls/edit.js
  addon/components/rdf-input-fields/remote-urls/show.js
  addon/components/rdf-input-fields/simple-value-input-field.js
  addon/components/rdf-input-fields/vlabel-opcentiem.js
  addon/components/submission-form.js
  addon/helpers/component-for-display-type.js
  addon/models/field.js
  addon/models/listing.js
  addon/models/section.js
  addon/models/sub-form.js
  addon/utils/display-type.js
  addon/utils/has-valid-field-options.js
  addon/utils/model-factory.js
  addon/utils/namespaces.js
  index.js
  package-lock.json
  package.json
  tests/dummy/app/controllers/form.js
  tests/dummy/app/mocks/handlers/files.js
  tests/dummy/app/routes/form.js
  tests/dummy/app/services/store.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
  tests/integration/helpers/is-last-test.js
  tests/unit/utils/display-type-test.js
  tests/unit/utils/register-form-fields-test.js
Labels: internal

#201 Dependency maintenance
  package-lock.json
  package.json
Labels: enhancement
